#!/bin/bash
# pywalの色からomarchyテーマを動的に生成するスクリプト
# Neovimは除外して、他のアプリのみpywalの色を適用

PYWAL_COLORS="$HOME/.cache/wal/colors.sh"
OMARCHY_THEME_DIR="$HOME/.config/omarchy/themes/pywal"

# pywalの色ファイルが存在しない場合は終了
if [ ! -f "$PYWAL_COLORS" ]; then
    echo "Error: pywal colors not found at $PYWAL_COLORS"
    exit 1
fi

# pywalの色を読み込む
source "$PYWAL_COLORS"

# omarchy pywalテーマディレクトリを作成
mkdir -p "$OMARCHY_THEME_DIR"

# ============================================================
# Ghostty 設定
# ============================================================
cat > "$OMARCHY_THEME_DIR/ghostty.conf" <<EOF
# Generated by pywal

# Basic colors
foreground = ${foreground}
background = ${background}
cursor-color = ${cursor}

# Selection
selection-foreground = ${foreground}
selection-background = ${color4}

# Terminal colors (0-15)
palette = 0=${color0}
palette = 1=${color1}
palette = 2=${color2}
palette = 3=${color3}
palette = 4=${color4}
palette = 5=${color5}
palette = 6=${color6}
palette = 7=${color7}
palette = 8=${color8}
palette = 9=${color9}
palette = 10=${color10}
palette = 11=${color11}
palette = 12=${color12}
palette = 13=${color13}
palette = 14=${color14}
palette = 15=${color15}
EOF

# ============================================================
# Kitty 設定
# ============================================================
cat > "$OMARCHY_THEME_DIR/kitty.conf" <<EOF
# Generated by pywal

# Basic colors
foreground ${foreground}
background ${background}
selection_foreground ${background}
selection_background ${foreground}

# Cursor colors
cursor ${cursor}
cursor_text_color ${background}

# URL underline color
url_color ${color4}

# Border colors
active_border_color ${color6}
inactive_border_color ${color8}
bell_border_color ${color1}

# Tab bar colors
active_tab_foreground ${background}
active_tab_background ${color4}
inactive_tab_foreground ${foreground}
inactive_tab_background ${color8}
tab_bar_background ${background}

# The 16 terminal colors
color0 ${color0}
color1 ${color1}
color2 ${color2}
color3 ${color3}
color4 ${color4}
color5 ${color5}
color6 ${color6}
color7 ${color7}
color8 ${color8}
color9 ${color9}
color10 ${color10}
color11 ${color11}
color12 ${color12}
color13 ${color13}
color14 ${color14}
color15 ${color15}
EOF

# ============================================================
# Hyprland 設定
# ============================================================
# HEXカラーをRGB形式に変換する関数
hex_to_rgb() {
    local hex=$1
    # #を削除
    hex=${hex#\#}
    # RGB値を抽出
    echo "${hex}"
}

ACTIVE_BORDER=$(hex_to_rgb "$color4")

cat > "$OMARCHY_THEME_DIR/hyprland.conf" <<EOF
# Generated by pywal
\$activeBorderColor = rgb(${ACTIVE_BORDER})

general {
    col.active_border = \$activeBorderColor
}

group {
    col.border_active = \$activeBorderColor
}
EOF

# ============================================================
# Hyprlock 設定
# ============================================================
cat > "$OMARCHY_THEME_DIR/hyprlock.conf" <<EOF
# Generated by pywal
\$background = rgb(${ACTIVE_BORDER})
EOF

# ============================================================
# Waybar CSS
# ============================================================
cat > "$OMARCHY_THEME_DIR/waybar.css" <<EOF
/* Generated by pywal */
@define-color foreground ${foreground};
@define-color background ${background};
EOF

# ============================================================
# Walker CSS
# ============================================================
cat > "$OMARCHY_THEME_DIR/walker.css" <<EOF
/* Generated by pywal */
@define-color foreground ${foreground};
EOF

# ============================================================
# SwayOSD CSS
# ============================================================
cat > "$OMARCHY_THEME_DIR/swayosd.css" <<EOF
/* Generated by pywal */
@define-color background ${background};
EOF

# ============================================================
# Neovim設定 - Catppuccinテーマを維持（pywalは適用しない）
# ============================================================
cat > "$OMARCHY_THEME_DIR/neovim.lua" <<EOF
-- Neovim theme is managed separately (Catppuccin)
-- This file is required by omarchy but not used
return {
	{
		"catppuccin/nvim",
		name = "catppuccin",
		priority = 1000,
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "catppuccin",
		},
	},
}
EOF

# ============================================================
# Alacritty設定
# ============================================================
cat > "$OMARCHY_THEME_DIR/alacritty.toml" <<EOF
# Generated by pywal
[colors.primary]
background = '${background}'
foreground = '${foreground}'

[colors.cursor]
text = '${background}'
cursor = '${cursor}'

[colors.normal]
black = '${color0}'
red = '${color1}'
green = '${color2}'
yellow = '${color3}'
blue = '${color4}'
magenta = '${color5}'
cyan = '${color6}'
white = '${color7}'

[colors.bright]
black = '${color8}'
red = '${color9}'
green = '${color10}'
yellow = '${color11}'
blue = '${color12}'
magenta = '${color13}'
cyan = '${color14}'
white = '${color15}'
EOF

# ============================================================
# Btop設定
# ============================================================
cat > "$OMARCHY_THEME_DIR/btop.theme" <<EOF
# Generated by pywal

theme[main_bg]="${background}"
theme[main_fg]="${foreground}"
theme[title]="${color4}"
theme[hi_fg]="${color6}"
theme[selected_bg]="${color8}"
theme[selected_fg]="${foreground}"
theme[inactive_fg]="${color8}"
theme[proc_misc]="${color3}"
theme[cpu_box]="${color4}"
theme[mem_box]="${color2}"
theme[net_box]="${color5}"
theme[proc_box]="${color6}"
theme[div_line]="${color8}"
theme[temp_start]="${color2}"
theme[temp_mid]="${color3}"
theme[temp_end]="${color1}"
theme[cpu_start]="${color4}"
theme[cpu_mid]="${color5}"
theme[cpu_end]="${color6}"
theme[free_start]="${color2}"
theme[free_mid]="${color3}"
theme[free_end]="${color6}"
theme[cached_start]="${color4}"
theme[cached_mid]="${color5}"
theme[cached_end]="${color6}"
theme[available_start]="${color2}"
theme[available_mid]="${color3}"
theme[available_end]="${color1}"
theme[used_start]="${color2}"
theme[used_mid]="${color3}"
theme[used_end]="${color1}"
theme[download_start]="${color2}"
theme[download_mid]="${color3}"
theme[download_end]="${color1}"
theme[upload_start]="${color4}"
theme[upload_mid]="${color5}"
theme[upload_end]="${color6}"
theme[process_start]="${color4}"
theme[process_mid]="${color5}"
theme[process_end]="${color6}"
EOF

# ============================================================
# ダミーファイル（omarchyが要求するファイル）
# ============================================================
echo "pywal-dynamic" > "$OMARCHY_THEME_DIR/chromium.theme"
echo "pywal-dynamic" > "$OMARCHY_THEME_DIR/icons.theme"
echo "{}" > "$OMARCHY_THEME_DIR/vscode.json"

# バックグラウンドディレクトリを作成（空でOK）
mkdir -p "$OMARCHY_THEME_DIR/backgrounds"

# Mako (通知デーモン) - 設定があれば
cat > "$OMARCHY_THEME_DIR/mako.ini" <<EOF
# Generated by pywal
background-color=${background}
text-color=${foreground}
border-color=${color4}
EOF

echo "✓ Pywal theme files generated at $OMARCHY_THEME_DIR"
